"""
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
"""
import math
import time


def divisors(n):
    factors_cnt = 0
    for i in range(1, int(math.ceil(math.sqrt(n))) + 1):
        if n % i == 0:
            factors_cnt += 2
        if i * i == n:
            factors_cnt -= 1
    return factors_cnt


def triangle_number(i):
    return (i * (i + 1)) / 2


if __name__ == '__main__':
    start = time.time()
    k = 10
    flag = True
    while flag:
        tri_num = triangle_number(k)
        divisors_cnt = divisors(tri_num)
        if divisors_cnt > 500:
            print(tri_num)
            print("Time required = ", time.time() - start)
            flag = False
        k += 1
